name: Build and deploy to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-server:
    name: Build Server
    runs-on: ubuntu-latest
    environment: production-server

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install pnpm
        run: |
          npm install -g pnpm
      
      - name: Initialize submodules
        run: |
          git config --global --add url."https://${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}:x-oauth-basic@github.com/".insteadOf "git@github.com:"
          git submodule update --init --recursive server

      - name: Write server .env file
        run: |
          cd server
          echo "NODE_ENV=production" > .env
          echo "PORT=8080" >> .env
          echo "DATABASE_URI=${{ secrets.DATABASE_URI }}" >> .env
          echo "PAYLOAD_SECRET=${{ secrets.PAYLOAD_SECRET }}" >> .env
          echo "CLIENT_URL=${{ vars.CLIENT_URL }}" >> .env
          echo "AZURE_STORAGE_CONNECTION_STRING=${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}" >> .env
          echo "AZURE_STORAGE_BASE_URL=${{ vars.AZURE_STORAGE_BASE_URL }}" >> .env

      - name: Install server dependencies and build
        run: |
          cd server
          pnpm install
          pnpm build
      
      - name: zip server artifact
        run: |
          (cd server; zip -rq --symlinks ../server-artifact.zip ./)

      - name: Upload server artifact
        uses: actions/upload-artifact@v3
        with:
          name: server-artifact
          path: server-artifact.zip

  build-client:
    name: Build Client
    runs-on: ubuntu-latest
    environment: production-client

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install pnpm
        run: |
          npm install -g pnpm
      
      - name: Initialize submodules
        run: |
          git config --global --add url."https://${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}:x-oauth-basic@github.com/".insteadOf "git@github.com:"
          git submodule update --init --recursive client

      - name: Write client .env file
        run: |
          cd client
          echo "NODE_ENV=production" > .env
          echo "PORT=8080" >> .env
          echo "NEXT_PUBLIC_SERVER_URL=${{ vars.NEXT_PUBLIC_SERVER_URL }}" >> .env
          echo "NEXT_PUBLIC_CLIENT_URL=${{ vars.NEXT_PUBLIC_CLIENT_URL }}" >> .env

      - name: Install client dependencies and build
        run: |
          cd client
          pnpm install
          pnpm build
      
      - name: zip client artifact
        run: |
          (cd client; zip -rq --symlinks ../client-artifact.zip ./)

      - name: Upload client artifact
        uses: actions/upload-artifact@v3
        with:
          name: client-artifact
          path: client-artifact.zip

  deploy-server:
    name: Deploy Server
    runs-on: ubuntu-latest
    needs:
      - build-server
      - build-client
    environment: 
      name: production-server
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download server artifact
        uses: actions/download-artifact@v3
        with:
          name: server-artifact

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
            app-name: ${{ vars.AZURE_SERVER_WEBAPP_NAME }}
            slot-name: 'production'
            publish-profile: ${{ secrets.AZURE_SERVER_WEBAPP_PUBLISH_PROFILE }}
            package: ./server-artifact.zip

  deploy-client:
    name: Deploy Client
    runs-on: ubuntu-latest
    needs: 
      - build-client
      - deploy-server
    environment: 
      name: production-client
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download client artifact
        uses: actions/download-artifact@v3
        with:
          name: client-artifact

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
            app-name: ${{ vars.AZURE_CLIENT_WEBAPP_NAME }}
            slot-name: 'production'
            publish-profile: ${{ secrets.AZURE_CLIENT_WEBAPP_PUBLISH_PROFILE }}
            package: ./client-artifact.zip